---
title: "Stat 128 Spring 2019 Term Project R Notebook"
output: html_notebook
author: "Kristin Van Gaasbeck"
---


# Stat 128 Term Project Data Source

1. Download from [UW Madison Courses and Grades 2006-2017](https://www.kaggle.com/Madgrades/uw-madison-courses)
(login required)
2. Local database: [sqlite: Mac OSX path](/Users/kvan/Downloads/data/uwm/database.sqlite3)
3. Local data files: [csv: Windows path](C:\Users\kvan\Downloads\data\uw-madison-courses)

-------------------------------------------------------- 

#Script to load the raw data - we may not need all of these files later on
#Imported from my desktop, after downloading from Kaggle.com

```{r}
course_offerings <- read.csv("~/Downloads/data/uwm/course_offerings.csv")
courses <- read.csv("~/Downloads/data/uwm/courses.csv")
grade_distributions <- read.csv("~/Downloads/data/uwm/grade_distributions.csv")
instructors <- read.csv("~/Downloads/data/uwm/instructors.csv")
rooms <- read.csv("~/Downloads/data/uwm/rooms.csv")
schedules <- read.csv("~/Downloads/data/uwm/schedules.csv")
sections <- read.csv("~/Downloads/data/uwm/sections.csv")
subject_memberships <- read.csv("~/Downloads/data/uwm/subject_memberships.csv")
subjects <- read.csv("~/Downloads/data/uwm/subjects.csv")
teachings <- read.csv("~/Downloads/data/uwm/teachings.csv")

```

#Question a) Compute average GPA of each section

```{r}
grades.sections <- merge(grade_distributions,sections,by.x=c('course_offering_uuid', 'section_number'), by.y=c('course_offering_uuid','number'))
summary(grades.sections)
```

#There are duplicates when matching the course_offering_uuid and section_number.

```{r}
library(plyr)  #useful for organizing and breaking down data for analysis
freq.of.course.and.section = count(grades.sections, vars=c('course_offering_uuid', 'section_number'))
sum(freq.of.course.and.section$freq>1) 

```

#17,507 duplicates; possibly a non-traditional format for the class such as co-taught or field work with multiple supervisers; 
#Or some sort of coding error. Visual inspection of these sections indicates they are identical in grade distribution
#Since they are identical in grade distribution, we want to delete the duplicates to avoid overweighting the duplicates in our analysis below


---------------------------------------------------------------------------

*END OF FILE* | 20190516 | Kristin Van Gaasbeck
